<!DOCTYPE html>
<style>
    .footer {
        position: absolute;
        right: 0;
        bottom: 0;
        left: 0;
        padding: 1rem;
        background-color: #efefef;
        text-align: center;
    }
</style>
<html lang="es">
    <head>
        <meta charset=<?= APP_CHARSET ?> >
        <title>Avanzapp</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <?php Tag::css('kumbia') ?>

        <?= Html::includeCss() ?>
<script   src="https://code.jquery.com/jquery-1.12.3.min.js"   integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ="   crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
            
    </head>
    <body>
        <div id="wrapper">
            <div id="header">
                <header class="row">
                    <div class="col-8">
                        <h2><?= Html::img('logo.png', 'Avante Logo') ?>
                        </h2>
                    </div>
                    <div class="col-4">

                    </div>
                </header>

                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">Menu</a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="#">Mapa <span class="sr-only">(current)</span></a></li>
                                <li><a href="#">Noticias</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administración <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><?echo Html::link("tipoestado", "Tipo estado")?></li>
                                        <li><?echo Html::link("tipotransporte", "Tipo transporte")?></li>
                                         <li><?echo Html::link("puntosruta", "Puntos ruta")?></li>                                        
                                        <li role="separator" class="divider"></li>
                                        <li><?echo Html::link("obra", "Obra")?></li>                                         
                                        <li><?echo Html::link("obraimagen", "Imagenes de obra")?></li>     
                                        <li role="separator" class="divider"></li>
                                        <li><?echo Html::link("notificacionapi", "Notificacion")?></li> 
                                    </ul>
                                </li>
                            </ul>
                           
                           
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>

            </div>
            <div class="container"><?php View::content() ?></div>
            <!--<div class="footer"><?php View::partial('kumbia/footer') ?></div>-->
        </div>
    </body>
</html>
